version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev_username
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: loan_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    working_dir: /app
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/loan_db
      SPRING_DATASOURCE_USERNAME: dev_username
      SPRING_DATASOURCE_PASSWORD: dev_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      JWT_SECRET: d92bbdddad6cdeaf6e2c08d486152ad544da8c92dfeafe7d7cfedbaa7f81955f15880d18e01d42856bfbae9287aae5195d5f21d3e6a3243fec54168c325ee2202a5970ab0847c91ea0a69b703e5f330b85cbd3f9a104d5394e1e5614cdbbabb2f52bb5755cc06dcd382a2865b24312f7aa71da7b9e6e58e589f69fc18662b0f417eb16b2f2135766ed141957023fa08efa354593b7d72aa1c632c00a7a3cd66ea90e7f03f4ae5a170201177cc3fabbcc9013e17c345b478117ae7fd7fd52f95e36849fe489b07f0f766ef6361cbf34e4189b7b8c3f45bb99638d63cd76caf4b0361efcfe971b1dab4ed64da3985d65e35d7a43ae1339e26c31b9597e52355974

volumes:
  postgres_data:
